name: absensi_app
description: Aplikasi Absensi Karyawan - Abha Hotel
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  google_maps_flutter: ^2.17.0
  http: ^1.2.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
